as yet unclassified
rosTypeDefinition 
^' int8 CHARGING_NOT_CHARGING=0
 int8 CHARGING_CHARGING_RECOVERY=1
 int8 CHARGING_CHARGING=2
 int8 CHARGING_TRICKLE_CHARGING=3
 int8 CHARGING_WAITING=4
 int8 CHARGING_CHARGING_ERROR=5
 std_msgs/Header header
 int8 bumps_wheeldrops
 bool wall
 bool cliff_left
 bool cliff_front_left
 bool cliff_front_right
 bool cliff_right
 bool virtual_wall
 int8 motor_overcurrents
 int8 dirt_detector_left
 int8 dirt_detector_right
 int8 remote_opcode
 int8 buttons
 int16 distance
 int16 angle
 int8 charging_state
 uint16 voltage
 int16 current
 int8 temperature
 uint16 charge
 uint16 capacity
'