as yet unclassified
rosTypeDefinition 
^' string name
 bool connected
 string ip
 string[] hub_names
 string[] hub_uris
 bool firewall
 gateway_msgs/Rule[] public_watchlist
 gateway_msgs/Rule[] public_interface
 gateway_msgs/RemoteRuleWithStatus[] flipped_connections
 gateway_msgs/RemoteRule[] flip_watchlist
 gateway_msgs/RemoteRule[] flipped_in_connections
 gateway_msgs/RemoteRule[] pull_watchlist
 gateway_msgs/RemoteRule[] pulled_connections
'