as yet unclassified
rosTypeDefinition 
^' int8 WIRED=1
 int8 WIRELESS=2
 int32 MAX_TTL=86400
 bool gateway_available
 int64 time_since_last_seen
 float32 ping_latency_min
 float32 ping_latency_max
 float32 ping_latency_avg
 float32 ping_latency_mdev
 bool network_info_available
 int8 network_type
 float32 wireless_bitrate
 int8 wireless_link_quality
 float32 wireless_signal_level
 float32 wireless_noise_level
'